server:
  port: 8088
spring:
  application:
    name: user-service
  cloud:
    nacos:
      config:
        username: xueyuan
        password: 123456
        server-addr: 127.0.0.1:8848
        namespace: xueyuan
        group: DEFAULT_GROUP
        file-extension: yaml, properties
      discovery:
        username: xueyuan
        password: 123456
        server-addr: 127.0.0.1:8848
        namespace: xueyuan
        group: DEFAULT_GROUP
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:mail-config.properties

logging:
  level:
    com.alibaba.cloud.nacos: INFO
    com.alibaba.nacos.client.config: INFO

security:
  login-whitelist:
    - /user/register
    - /user/login
    - /user/send-code

operation-log:
  enabled: true
