server:
  port: 8088
spring:
  application:
    name: user-service
  cloud:
    nacos:
      config:
        username: xueyuan
        password: 123456
        server-addr: 127.0.0.1:8848
        namespace: xueyuan
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        username: xueyuan
        password: 123456
        server-addr: 127.0.0.1:8848
        namespace: xueyuan
        group: DEFAULT_GROUP
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:encrypt-config.yml

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos.client.config: DEBUG

